# SMT Python Seminar - Matrices and vectors

* matrix/vector manipulations with `numpy`

## Enabling some magic

More on the Jupyter magic commands: https://alexsm.com/jupyter-notebook-ipython-magic/

In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

<IPython.core.display.Javascript object>

## Imports

In [3]:
import numpy as np
import random

## Demo with `numpy`

In [4]:
v0 = np.array([1, 0, 2])
v0

array([1, 0, 2])

In [5]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
A = np.random.randint(0, 11, size=(3, 3))
A

array([[ 5,  7,  8],
       [ 8,  9,  9],
       [ 3,  6, 10]])

In [7]:
np.dot(A, I)

array([[ 5.,  7.,  8.],
       [ 8.,  9.,  9.],
       [ 3.,  6., 10.]])

In [8]:
np.linalg.matrix_rank(A)

3

In [9]:
A_inv = np.linalg.inv(A)
A_inv

array([[-1.56521739,  0.95652174,  0.39130435],
       [ 2.30434783, -1.13043478, -0.82608696],
       [-0.91304348,  0.39130435,  0.47826087]])

In [10]:
v1 = np.dot(A, v0)
v1

array([21, 26, 23])

In [11]:
np.dot(A_inv, v1)

array([1.00000000e+00, 3.55271368e-15, 2.00000000e+00])